crm/admin/views.py
# -*- coding: utf-8 -*-
"""
    crm.admin.views
    ~~~~~~~~~~~~~~~
"""

from flask import (
    render_template, request, Blueprint, redirect, url_for, g)
from flask.ext.login import (login_user, login_required, logout_user,
                             current_user)

from crm.core import db
from crm.domain.users import service
from crm.tools.token import Token, get_token
from crm.domain import ApplicationError
from crm.domain.system.service import *

import forms
from crm.domain.users.models import *
import crm.domain.users.service as user_service

bp = Blueprint('admin', __name__, static_folder='static')


def load_user(userid):
    return User.query.get(userid)


@bp.route('/')
@login_required
def index():
    return render_template('dashboard.html')


@bp.route('/users/token', methods=['GET', 'POST'])
@login_required
def users_token():
    form = forms.UserTokenForm()
    if request.method == 'POST' and form.login.data and form.validate():
        try:
            from hashlib import sha1
            password = sha1(form.password.data).hexdigest().lower()
            user = service.authenticate(form.login.data, password)
            user_token = Token({
                'uid': user.id,
                'gid': 0
            })
            token = user_token.generate()
            form.token.data = token
            form.decode.data = vars(get_token(token))
        except ApplicationError as e:
            form.login.errors.append(str(e))
    if request.method == 'POST' and form.token.data:
        try:
            form.decode.data = vars(get_token(form.token.data))
        except ApplicationError as e:
            form.login.errors.append(str(e))
    return render_template('users_token.html', form=form)


@bp.route('/system/logs', methods=['GET', 'POST'])
@login_required
def system_logs():
    form = forms.SystemLogsSearchForm()
    from crm.domain.system.models import Log
    logs = Log.query.all()
    return render_template('system_logs.html', form=form, logs=logs)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if g.user is not None and g.user.is_authenticated():
        return redirect(url_for('admin.index'))
    form = forms.LoginForm()
    if form.validate_on_submit():
        try:
            from hashlib import sha1
            password = sha1(form.password.data).hexdigest().lower()
            user = user_service.authenticate(form.login.data, password)
            # if not user.has_role(User.Role.admin):
            #     logout_user()
            #     raise ValidationError('Only users that have admin role can \
            #                           login here')
            if user is not None:
                log_info('Admin user login {0}'.format(user.full_name()),
                         user.id)
                db.session.commit()
                login_user(user)
                return redirect(request.args.get('next') or
                                url_for('admin.index'))
        except ApplicationError as e:
            form.login.errors.append(str(e))
    return render_template('login.html', form=form)


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('admin.login'))


@bp.before_request
def before_request():
    g.user = current_user

crm/admin/templates/dashboard.html
{% extends 'layout.html' %}

{% block head %}
    <title>Dashboard</title>
    <style>
        .menublock {
            width: 400px;
            background-color: #fff;
            margin: 15px;
            padding: 10px;
            float: left;
            border-radius: 4px;
        }
        .menublock .title {
            font-weight: bold;
        }
        .menublock a {
            color: #000;
        }
        .menublock ul {
            list-style-type: square;
            margin-bottom: 3px;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="menublock">
        <span class="title">
            <span class="glyphicon glyphicon-floppy-disk"></span> Administrative
        </span>
        <ul>
            <li><a href="{{ url_for('admin.users_token') }}">Token operations</a></li>
        </ul>
        <ul>
            <li><a href="{{ url_for('admin.system_logs') }}">System logs</a></li>
        </ul>
    </div>
    <div class="menublock">
        <span class="title">
            <span class="glyphicon glyphicon glyphicon-list-alt"></span> Tables
        </span>
        <ul>
            <li><a href="/admin/flask-models/userview/" target="_blank">Users</a></li>
        </ul>
        <ul>
            <li><a href="/admin/flask-models/taskview/" target="_blank">Tasks</a></li>
        </ul>
        <ul>
            <li><a href="/admin/flask-models/projectview/" target="_blank">Projects</a></li>
        </ul>
        <ul>
            <li><a href="/admin/flask-models/clientview/" target="_blank">Clients</a></li>
        </ul>
        <ul>
            <li><a href="/admin/flask-models/jobview/" target="_blank">Jobs</a></li>
        </ul>
    </div>
{% endblock %}

crm/admin/templates/layout.html
<!DOCTYPE html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://yandex.st/bootstrap/3.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('.static', filename='main.css') }}">

    {% block head %}
    {% endblock %}
</head>

<body>
    <!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    {% if g.user.is_authenticated() %}
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('admin.index') }}">CRM</a>
        </div>
        <div class="collapse navbar-collapse ">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('admin.index') }}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <p class="navbar-text">Logged in as <strong><em>{{ g.user.full_name() }}</em></strong></p>
                <li><a href="{{ url_for('admin.logout') }}">Logout</a></li>
            </ul>
        </div>
    </div>
    {% endif %}

    <div class="container">
    {% block body %}
    {% endblock %}
    </div>
</body>

</html>

crm/admin/templates/login.html
{% extends 'layout.html' %}

{% block head %}
    <title>Login</title>
{% endblock %}

{% block body %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h2 class="panel-title">Login form</h2>
        </div>

        <div class="panel-body">
            {% if form.errors %}
                <div>
                    <ul class="errors">
                        {% for name, errors in form.errors|dictsort if errors %}
                            {% for error in errors %}
                                <li>{{ form[name].label }}: {{ error }}</li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            <form method="POST">
                {{ form.hidden_tag() }}
                <table class="form">
                    <tr>
                        <td class="desc"><label>Login:</label></td>
                        <td>{{ form.login }}</td>
                    </tr>
                    <tr>
                        <td class="desc"><label>Password:</label></td>
                        <td>
                            {{ form.password }}
                        </td>
                    </tr>
                    <tr>
                        <td class="desc"></td>
                        <td><input type="submit" /></td>
                   </tr>
                </table>
            </form>
        </div>
    </div>
{% endblock %}

crm/admin/templates/system_logs.html
{% extends 'layout.html' %}

{% block head %}
    <title>System - Logs</title>
{% endblock %}

{% block body %}
    {% if form.errors %}
        <div class="alert alert-danger">
            {% for field_name, field_errors in form.errors|dictsort if field_errors %}
                {% for error in field_errors %}
                    <li>{{ form[field_name].label }}: {{ error }}</li>
                {% endfor %}
            {% endfor %}
        </div>
    {% endif %}

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h2 class="panel-title">Logs</h2>
        </div>
        <div class="panel-body">
            <form method="GET">
                {{ form.hidden_tag() }}
                <table class="form">
                    <tr>
                        <td class="desc"><label>Text:</label></td>
                        <td>{{ form.text() }}</td>
                        <td><input type="submit" value="Search" class="btn btn-primary" /></td>
                    </tr>
                </table>
            </form>
        </div>
  	</div>

    <table class="table table-striped table-hover">
        <tr>
            <th>Text</th>
            <th>Created</th>
        </tr>
        {% for log in logs %}
        <tr>
            <td>{{ log.text }}</td>
            <td>{{ log.created }} </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

crm/admin/templates/users_token.html
{% extends 'layout.html' %}

{% block head %}
    <title>Users - Token</title>
{% endblock %}

{% block body %}
    {% if form.errors %}
        <div class="alert alert-danger">
            {% for field_name, field_errors in form.errors|dictsort if field_errors %}
                {% for error in field_errors %}
                    <li>{{ form[field_name].label }}: {{ error }}</li>
                {% endfor %}
            {% endfor %}
        </div>
    {% endif %}

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h2 class="panel-title">Token generator form</h2>
        </div>

        <div class="panel-body">
            <form method="POST">
                {{ form.hidden_tag() }}
                <table class="form">
                    <tr>
                        <td class="desc"><label>Login:</label></td>
                        <td>{{ form.login() }}</td>
                    </tr>
                    <tr>
                        <td class="desc"><label>Password:</label></td>
                        <td>
                            {{ form.password }}
                        </td>
                    </tr>
                    <tr>
                        <td class="desc"></td>
                        <td><input type="submit" value="Get" class="btn btn-primary" /></td>
                    </tr>
                    <tr class="hr">
                        <td class="desc">Token:</td>
                        <td id='token-plain'>{{ form.token.data }}</td>
                    </tr>
                    <tr class="hr">
                        <td class="desc">Copy token:</td>
                        <td><button id="token-copy" class="btn">Copy clipboard</button></td>
                    </tr>
                    <tr>
                        <td class="desc">User ID:</td>
                        <td>{{ form.user_id.data }}</td>
                    </tr>
                </table>
            </form>
        </div>
    </div>

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h2 class="panel-title">Token decode form</h2>
        </div>

        <div class="panel-body">
            <form method="POST">
                {{ form.hidden_tag() }}
                <table class="form">
                    <tr>
                        <td class="desc"><label>Token:</label></td>
                        <td>{{ form.token(class = 'width-5') }}</td>
                    </tr>
                    <tr>
                        <td class="desc"></td>
                        <td><input type="submit" value="Decode" class="btn btn-primary" /></td>
                    </tr>
                    <tr class="hr">
                        <td class="desc">Data:</td>
                        <td>{{ form.decode.data }}</td>
                    </tr>
                </table>
            </form>
        </div>
    </div>

    <script>
        document.getElementById('token-copy').onclick = function() {
            var text = document.getElementById('token-plain').innerHTML;
            window.prompt("Copy to clipboard: Ctrl+C, Enter", text);
            return false;
        }
    </script>
{% endblock %}